# fly.toml app configuration file generated for petstore-blue-cloud-8985 on 2024-11-11T08:50:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'petstore'
primary_region = 'bos'

[build]
  [build.args]
    GO_VERSION = '1.23.4'

[http_service]
  internal_port = 54321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.http_options]
    h2_backend = true
  [http_service.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.2", "TLSv1.3"]
    default_self_signed = false


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
