# https://fly.io/docs/reference/configuration/
app = "petstore"
primary_region = "bos"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true

[[http_service.checks]]
method = "GET"
path = "/health"
interval = "5s"
timeout = "4s"
