app = "petstore"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[[services]]
protocol = "tcp"
internal_port = 54321
processes = ["app"]

[[services.ports]]
handlers = ["tls", "http"]
port = 443
tls_options = { "alpn" = ["h2"] }
